name: Build Blogs Index Action
on:
  push: 
    branches: 
      - master
    paths:
      - blogs/**
    
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 'v19.3.0'

      - name: Install packages && Running Index content generate script.
        run: |
          npm ci
          npm run build-blogindex
          echo "INDEX_FILE_CONTENT_VAR<<EOF" >> $GITHUB_ENV
          echo $(cat build/blogIndex.md) >> $GITHUB_ENV 
          echo "EOF" >> $GITHUB_ENV

      - name: Modify test test/overwrite.file.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          branch: master
          path: blogIndex.md
          body: 'Hey \n hi'
          overwrite: 'true'
          committer_name: 'action-system'
          message: 'blogs updated.'
          
        
